### ISSUE TITLE
Unable to re-dump artwork

### ISSUE THREAD

**Issue by roidy** [rmrector/script.artwork.dump#1]
https://forum.kodi.tv/showthread.php?tid=258886&pid=2996615#pid2996615

If you delete dumped artwork from your drive you can no longer dump it again without first either changing the artwork or refreshing the movie/tv show.

**Comment by rmrector** [comment]
What? Don't delete it if you want to keep it. That's not how this was designed. It downloads artwork then changes the path to point to the newly downloaded artwork.

The whole point of downloading artwork once is so that Kodi doesn't have to download things over and over again. If you are using this tool to redownload the same thing then what's the point?

**Comment by roidy** [comment]
Ok, thanks I understand how it works now, I didn't realise it changed the path in the database.
